#ifndef __DEFINITION_H__
#define __DEFINITION_H__


#define BEGIN_NAMESPACE_CA namespace CodeAdapter {
#define END_NAMESPACE_CA }

#define BEGIN_NAMESPACE_CA_DRAWING BEGIN_NAMESPACE_CA namespace Drawing {
#define END_NAMESPACE_CA_DRAWING } END_NAMESPACE_CA

#define BEGIN_NAMESPACE_CA_AUDIO BEGIN_NAMESPACE_CA namespace Audio {
#define END_NAMESPACE_CA_AUDIO } END_NAMESPACE_CA

#define BEGIN_NAMESPACE_CA_SYSTEM BEGIN_NAMESPACE_CA namespace System {
#define END_NAMESPACE_CA_SYSTEM } END_NAMESPACE_CA

#define BEGIN_NAMESPACE_CA_NETWORK BEGIN_NAMESPACE_CA namespace Network {
#define END_NAMESPACE_CA_NETWORK } END_NAMESPACE_CA

#define BEGIN_NAMESPACE_CA_UTILITY BEGIN_NAMESPACE_CA namespace Utility {
#define END_NAMESPACE_CA_UTILITY } END_NAMESPACE_CA


#endif